---
- name: Install Ovirt Tools on Centos VM
  hosts: all
  gather_facts: yes
  tasks:
    - name: Add Ovirt Repository
      yum:
        name: 'centos-release-ovirt42'
        state: latest

    - name: Install Ovirt Tools
      yum:
        name: 'ovirt-guest-agent-common'
        state: latest

    - name: Remove Ovirt Repository
      yum:
        name: 'centos-release-ovirt42'
        state: absent

    - name: Enable Ovirt Guest Tools
      systemd:
        state: started
        name: ovirt-guest-agent