# https://docs.ansible.com/ansible/2.5/modules/win_updates_module.html#win-updates-module
---
- name: Windows Updates Sample Playbook
  hosts: all

  tasks:
  - name: Windows Updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      state: installed
    register: update_result
