# https://docs.ansible.com/ansible/2.5/modules/win_chocolatey_module.html#win-chocolatey-module
---
- name: chcolatey sample playbook
  hosts: all
  gather_facts: no

  tasks:
  - win_chocolatey:
      name: procexp
      state: present